newVersionCheck:
  enabled: false
library:
  scan:
    enabled: false
storageTemplate:
  enabled: false
server:
  loginPageMessage: |
    This is a demo instance of Immich. It is regularly reset. <br>
    
    <b style='color: red'>Due to abuse, uploads to this instance are disabled.</b><br><br>

    <a class="underline" href="javascript:
      email = document.getElementById('email');
      email.value = 'demo|immich.app'.replace('|', '@');
      email.dispatchEvent(new Event('input', { bubbles: true }));
      password = document.getElementById('password');
      password.value = 'demo';
      password.dispatchEvent(new Event('input', { bubbles: true }));
      document.forms[0].requestSubmit();
    ">Login as demo user</a>
